const gradeThreePeony: string[] = [
    "Adarsh S. Baghel",
    "Akarsh P. Singh",
    "Alisha Ranjan",
    "Aryan Verma",
    "Atharv Dwivedi",
    "Ayu Shukla",
    "Devansh Tripathi",
    "Gauravi Singh",
    "Hridansh Shandilya",
    "Martand Singh",
    "Manvi Tiwari",
    "Prakriti Pandey",
    "Pranavi Napit",
    "Pratham Tharwani",
    "Radhya Gupta",
    "Riyansh Mishra",
    "Rudra Thapar",
    "Samaira Singh",
    "Samridhi Tamrakar",
    "Sarthak Tharwani",
    "Satvik Singh",
    "Shilpi Singh",
    "Shivansh Lalwani",
    "Shreya Pandey",
    "Tanaya Motwani",
    "Varinika Mishra",
    "Vidhan Khandelwal",
    "Vidhi Khandelwal",
    "Vivan Yadav",
    "Yamya Singh"
].sort();

const gradeOnePeony: string[] = [
    "Aadvik Kotwani",
    "Aaradhya Singh",
    "Aarush Dwivedi",
    "Achyut Gupta",
    "Adveka Gautam",
    "Anshika Singh",
    "Arsh Singh Baghel",
    "Arya Sondhiya",
    "Aryahi Singh",
    "Aryan Singh Gaharwar",
    "Devansh Pratap Singh",
    "Faiza Siddiqui",
    "Ganesh Naayan",
    "Garvit Chaurasiya",
    "Ishanvi Shukla",
    "Kavya Shrivastav",
    "Keyan Malkani",
    "Kritika Gupta",
    "Maharshi Pathak",
    "Naira Ansari",
    "Parth Tiwari",
    "Riddhant Gupta",
    "Rudra Pandey",
    "Samriddhi Singh",
    "Sarvam Singh",
    "Shivaan Shukla",
    "Shreya Pandey",
    "Swastik Chaturvedi",
    "Vedansh Patel",
    "Veeksha Shukla",
    "Viraj Gupta",
    "Vivaansh Pandey",
    "Prateek Singh",
    "Shurya Vardhan Singh"
].sort();

const gradeFourIris: string[] = [
    "Aaradhya Singh",
    "Aarohan Khemchandani",
    "Amaira Chandwani",
    "Amaya Chaturvedi",
    "Anujaney Singh",
    "Anvi Tiwari",
    "Apeksha Mishra",
    "Arpit Gupta",
    "Arya Mishra",
    "Divya Narayan Shukla",
    "Divyaraj Singh",
    "Eshan Pandey",
    "Jash Chauhan",
    "Mamleshwar Singh Dev",
    "Nyshita Singh",
    "Parv Pandey",
    "Pratyush Singhraul",
    "Riddhima Tharwani",
    "Sakshi Gupta",
    "Sarvagya Mishra",
    "Shaurya Shukla",
    "Sheryl Chandwani",
    "Srishti Singh",
    "Tanishq Ku. Kushwaha",
    "Tejsawaini Gautam",
    "Vaibhav Singh Thakur",
    "Viraj Pratap Singh",
    "Yaksh Nagwani"
].sort();

const gradeFourBluebell = [
    "Abhay Choudhary",
    "Adamya Tripathi",
    "Akshita Mishra",
    "Anika Singh",
    "Anjali Patel",
    "Aradhya Giri",
    "Aradhya Singh Sisodiya",
    "Arnav Kol",
    "Arshika Tiwari",
    "Aryaman Singh",
    "Atharv Pandey",
    "Barish Yadav",
    "Hemansh Tiwari",
    "Kairavi Ahuja",
    "Kartik Tiwari",
    "Nivanshi Mishra",
    "Pragya Kushwaha",
    "Praman Pandey",
    "Sanskriti Mishra",
    "Sanskriti Suman",
    "Sarvagya Shukla",
    "Smera Pareek",
    "Tashvi Panjwani",
    "Vaishnavi Pandey",
    "Varenya Vijayvargiya"
].sort();

const gradeFourPeony = [
    "Aadya Gupta",
    "Advik Pandey",
    "Akriti Singh",
    "Akshita Tiwari",
    "Anaya Mishra",
    "Anaya Shukla",
    "Dhwija Pasari",
    "Divyansh Patel",
    "Kavya Singh",
    "Medhansh Saxena",
    "Navya Singh",
    "Nityashree Tripathi",
    "Rajveer Tharwani",
    "Reyansh Singh Parihar",
    "Rudra Abhishek Pandey",
    "Rudra Singh Baghel",
    "Runav Mishra",
    "Sarvagya Pandey",
    "Shail Tiwari",
    "Shanvi Keshri",
    "Swarnim Tripathi",
    "Tanishq Singh Tiwari",
    "Uplaksh Mishra",
    "Virat Singh",
    "Vivek Chaturvedi",
    "Yessica Lalwani"
].sort();

const gradeThreeIris = [
    "Aaban Alam",
    "Aarunya Upadhya",
    "Abhyuday Pratap Singh",
    "Advik Patel",
    "Advik Singh Tiwari",
    "Amairadeep",
    "Amyra Vandre",
    "Anant Mihani",
    "Anaya Krishnani",
    "Ankur Mihani",
    "Aryan Mishra",
    "Ayushman Soneta",
    "Dhrishti Modanwal",
    "Hanika Hanspal",
    "Hardik Khemchandani",
    "Harshal Mishra",
    "Ilisha Mishra",
    "Keisha Dubey",
    "Namreeti Shah",
    "Nidhipa Manshani",
    "Reyansh Patel",
    "Rishi Singh",
    "Rudransh Dwivedi",
    "Shrishti Modanwal",
    "Siyanshi Singh",
    "Shubhali Mishra",
    "Shubham Tiwari",
    "Suraj Tiwari",
    "Vishwas Verma",
    "Aadrika Singh"
].sort();

const gradeThreeBluebell = [
    "Abhideep",
    "Abhira Yadav",
    "Aditi Prajapati",
    "Advik Pandey",
    "Akshat Pratap Singh",
    "Animesh Tripathi",
    "Arjun Pratap Singh",
    "Arohi Mishra",
    "Arya Singh",
    "Ashruti Singh",
    "Atharva Gautam",
    "Atharva Jaipuriya",
    "Atharva Kumar Pandey",
    "Deepika Pandey",
    "Devansh Tiwari",
    "Gaurang Pratap Singh",
    "Jaskirat Singh Dang",
    "Kashvi Dwivedi",
    "Kartik Singh Dubey",
    "Kaustubh Tiwari",
    "Krisha Pandey",
    "Mukti Mishra",
    "Navneet Nagwani",
    "Nitya Singh",
    "Pratyush Gangwani",
    "Reyansh Gupta",
    "Rudra Pratap Singh",
    "Saksham Chikara",
    "Sarang Singh",
    "Tanuja Singh Patel"
].sort();

const gradeTwoBluebell = [
    "Aayansh Tiwari",
    "Aayukta Singh",
    "Akshdeep Singh Siddhu",
    "Arush Patel",
    "Aryadev Singh Gaharwar",
    "Ashreya Singh Sengar",
    "Atharva C. Nair",
    "Devasy Singh",
    "Dev Tripathi",
    "Dikshant Pathak",
    "Ginika Ledwani",
    "Kavya Dubey",
    "Myra Fatima Ansari",
    "Nilakshi Gupta",
    "Parth Lohare",
    "Ridhan Meshram",
    "Shambhavi Singh",
    "Shashank Dubey",
    "Shourya Pratap Singh Parihar",
    "Souravi Chaurasiya",
    "Tanisha Tiwari",
    "Tishya Singh",
    "Vishrut Mishra",
    "Vivaan Singh",
    "Yashi Singh Parihar"
].sort();

const gradeTwoPeony = [
    "Aadesh Atharva",
    "Aakansh Gautam",
    "Adisa Patel",
    "Amol Gupta",
    "Arayna Tiwari",
    "Ashwath Chaurasiya",
    "Atharv Sinh",
    "Ditya Chaurasiya",
    "Dixesh Verma",
    "Gyanendra Prasad Tiwari",
    "Harleen Kaur Duggal",
    "Kavish Mishra",
    "Krishna Shukla",
    "Manasvini Singh",
    "Manya Mishra",
    "Nomaan Aziz Siddiqui",
    "Pakhi Patel",
    "Praham Gangwani",
    "Prisha Gautam",
    "Rayansh Singh",
    "Rishabh Dubey",
    "Shreyansh Tripathi",
    "Surya Pratap Singh",
    "Swar Gupta",
    "Tasmiya Ara",
    "Udit Narayan Shukla",
    "Vishnu Rohit Tiwari"
].sort();

const gradeTwoIris = [
    "Aarush Singh",
    "Amey Kumar Mishra",
    "Anidhya Dwivedi",
    "Atharva Mishra",
    "Avyaan Pandey",
    "Ayansh Mishra",
    "Dhriti Mishra",
    "Indrakshi Verma",
    "Krishnam Saket",
    "Nysha Tekwani",
    "Parth Singh",
    "Rudransh Singh",
    "Saarya Pandey",
    "Samiksha Choudhari",
    "Sanskara Yadav",
    "Shivanya Pandey",
    "Shivay Sharma",
    "Shreem Shukla",
    "Suryansh Pratap Singh Parihar",
    "Swatantra Tiwari",
    "Syed Arham Ali",
    "Vaani Mohnani",
    "Vaishnavi Singh Parihar",
    "Vedika Srivastava",
    "Vivaan Jaiswal",
    "Kartik Sen"
].sort();


const gradeFiveIris = [
    "Aaryav Gupta",
    "Adrika Sohgaura",
    "Advik Goyal",
    "Anjaneya Shrivastav",
    "Ankush Patel",
    "Anupam Sahu",
    "Anupriya Singh",
    "Arnav Tiwari",
    "Aryawardhan Singh",
    "Aseem Jotwani",
    "Ashutosh Gupta",
    "Atharv Singh Chauhan",
    "Ayush Mohnani",
    "Devansh Singh Tiwari",
    "Dhairya Motwani",
    "Divyansh Gautam",
    "Garvit Trivedi",
    "Hridya Mishra",
    "Kanishka Shrivastav",
    "Manu Singh",
    "Nami Singh",
    "Natisha Singh",
    "Nirbhika Kesri",
    "Parth Pandey",
    "Rudraksh Mishra",
    "Sanjog Singh Kalra",
    "Shanaya Khurana",
    "Shani Mishra",
    "Sheikh Arhan",
    "Shubhangi Singh",
    "Snehal Yadav",
    "Svarnim Pandey",
    "Tanishq Tilkar",
    "Tanya Singh",
    "Vanya Singh",
    "Vibhuti Narayan Mishra",
    "Arnav Singh"
].sort();

const gradeSixIris = [
    "Aaradhya Pathak",
    "Aarna Tondon",
    "Aditi Panjwani",
    "Aditi Sharma",
    "Advika Bain",
    "Advika Goswami",
    "Aliya Ansari",
    "Anshumaan Sharma",
    "Aranya Kol",
    "Arnavi Gautam",
    "Astitva Dubey",
    "Avantika Singh",
    "Ayushman Pandey",
    "Divyansh Chaurasia",
    "Harry Lekhwani",
    "Harshit Gupta",
    "Humera Saleha Ansari",
    "Ishi Singh",
    "Jairaj Singh",
    "Jashvin Kaur",
    "Jenisha Tanwani",
    "Kanishka Gautam",
    "Kavya Pandey",
    "Mahak Tharwani",
    "Meenakshi Singh",
    "Ojas Gupta",
    "Pratyush Singh",
    "Ratnam Singh",
    "Rudransh Archana Pandey",
    "Sarthak Gupta",
    "Shreyash Gupta",
    "Sirjan Singh Dang",
    "Tanishk Tiwari",
    "Vansh Kakwani",
    "Vipanchi Gautam",
    "Zyana Swamy"
].sort();

const gradeSixPeony = [
    "Aalekhya Singh Baghel",
    "Aarav Gupta",
    "Aarav Jhamwani",
    "Aarav Singh",
    "Aarya Gupta",
    "Aayasha Singh",
    "Abhay Meena",
    "Abhigyan Tiwari",
    "Aditi Raje Singh",
    "Aditya Rajya Singh",
    "Advit Pandey",
    "Aradhya Singh Baghel",
    "Atharv Singh",
    "Mritunjay Dwivedi",
    "Om Singh",
    "Pratyansh Singh Baghel",
    "Purti Pandey",
    "Purvi Singh",
    "Rajveer Singh",
    "Rdra Raj Tamrakar",
    "Riya Chaturvedi",
    "Rudra Mishra",
    "Sanjeev Patel",
    "Shloktika Singh Gharwar",
    "Shriyanshi Gupta",
    "Siddhi Gupta",
    "Viraj Singh Chauhan",
    "Yashika Singh",
    "Yashwardhan Yadav"
].sort();

const gradeSevenIris = [
    "Anubhav Dwivedi",
    "Anushka Singh Parihar",
    "Aradhya Gupta",
    "Aradhya Pasari",
    "Ayra Khan",
    "Ayush Singh",
    "Geet Kaur",
    "Hardik Jhamwani",
    "Jayesh Khushlani",
    "Kaustubh Singh",
    "Kiara Khan",
    "Kritik Sharma",
    "Kunwar Singh Bharti",
    "Linisha Saxena",
    "Pallawi Vishwakarma",
    "Priyamvda Singh",
    "Rajveer Arya",
    "Rapunzel Patel",
    "Shambhavi Singh Parihar",
    "Shaurya Gupta",
    "Shresth Singh",
    "Siddharth Mishra",
    "Vansh Sahu",
    "Vedyansh Singh Parihar",
    "Yuvan Pandey"
].sort();

const gradeOneIris = [
    "Aadvik Singh",
    "Arush Singh Baghel",
    "Aditya Sharma",
    "Advita Kohli",
    "Anya Sharma",
    "Anayra Hotwani",
    "Anay Sharma",
    "Anshuman Pathak",
    "Aryaditya Singh Baghel",
    "Asvith Dixit",
    "Atulit Vishisht",
    "Ayush Mishra",
    "Aaryansh Shukla",
    "Daniya Aziz Siddiqui",
    "Devaditya Singh",
    "Dhruv Singh",
    "Pranav Mishra",
    "Pranshi Tiwari",
    "Parth Goyal",
    "Reyansh Pandey",
    "Ridhanya Singh",
    "Rudra Pratap Singh",
    "Shaarvi Sharma",
    "Shravya Gupta",
    "Tavishi Rohra",
    "Vansh Vardhan Singh",
    "Varenya Gupta",
    "Vidyashankar Pathak",
    "Vihaan Mishra",
    "Zohra Fatima Khan",
    "Shrishti Mishra",
    "Arna Gupta",
    "Shashwat Mishra",
    "Supriya Singh Thakur"
].sort();

const gradeSevenPeony = [
    "Aakash Kakwani",
    "Aanya Singh",
    "Aarna Dwivedi",
    "Aarohi Khandelwal",
    "Aayush Singh",
    "Abhiram Pandey",
    "Abisha Fatima",
    "Aksh Rangrez",
    "Akshay Soni",
    "Anshuman Tripathi",
    "Arpita Sahu",
    "Daksh Hotwani",
    "Divyansh Kushwaha",
    "Huzaifa Khan",
    "Jainil Tanwani",
    "Jatin Ramwani",
    "Maulik Bajaj",
    "Parth Gupta",
    "Raghvendra Tiwari",
    "Samraddh Gupta",
    "Sanvi Gupta",
    "Saanvika Suman",
    "Sayhan Ali",
    "Suryansh Sharma",
    "Yuvraj Singh"
].sort();

const gradeFivePeony = [
    "Aadya Tripathi",
    "Aarav Singh",
    "Admaya Shukla",
    "Allina Khilwani",
    "Anshka Sahu",
    "Anvi Ojha",
    "Arjan Khan",
    "Arnabh Mishra",
    "Asmi Mishra",
    "Daivik Kumar Patel",
    "Dhairya Mihani",
    "Divyanshu Dwivedi",
    "Hirisha Lahori",
    "Hunzala Khan",
    "Ichcha Shukla",
    "Kaustubh Tripathi",
    "Krish Kotwani",
    "Kritarth Singh Parihar",
    "Mrityunjay Tamrakar",
    "Ojas Selkar",
    "Rajveer Mohnani",
    "Rajvi Pandey",
    "Ranvijay Singh",
    "Rishika Singh",
    "Triksha Prabhakar",
    "Vidit Patel",
    "Yugvardhan Singh",
    "Sahil Singh",
    "Prithvi Tiwari",
    "Jignesh Patel",
    "Adya Tiwari",
    "Sarvesh Singh Parihar"
].sort();

export const gradeWiseStudentsList: { [index: string]: string[] }[] = [
    {
        "Iris": gradeOneIris,
        "Peony": gradeOnePeony
    },
    {
        "Iris": gradeTwoIris,
        "Peony": gradeTwoPeony,
        "Bluebell": gradeTwoBluebell
    },
    {
        "Iris": gradeThreeIris,
        "Peony": gradeThreePeony,
        "Bluebell": gradeThreeBluebell
    },
    {
        "Iris": gradeFourIris,
        "Peony": gradeFourPeony,
        "Bluebell": gradeFourBluebell
    },
    {
        "Iris": gradeFiveIris,
        "Peony": gradeFivePeony,
    },
    {
        "Iris": gradeSixIris,
        "Peony": gradeSixPeony
    },
    {
        "Iris": gradeSevenIris,
        "Peony": gradeSevenPeony
    }
];